### ISSUE TITLE
1.0 Release punchlist

### ISSUE THREAD

**Issue by twojtasz** [uber/xviz#456]
# code complete tasks
- [ ] @xviz/io module #435 
- [ ] @xviz/server release #453
- [ ] @xviz/ros release ?
- [ ] state_update type  #446 
- [ ] log_info schema #448 
- [ ] @loaders.gl v1.1 update

- [ ] alititude and maps (streetscape.gl) [320](https://github.com/uber/streetscape.gl/pull/320)

# Prerelease package
- [ ] Frame -> Message renaming post landing #454

- [ ] changelog
  - Mainly new modules + performance improvements
- [ ] faq
  - [ ] [FAQ Doc](https://docs.google.com/document/d/1RRyQ9yySM-TbDcOh6OiFfxEHvRMsqOyGcrzhjYrWMWg/edit) [Tim's list to reconcile](https://docs.google.com/document/d/1FjfBSFi0LAvnx8QdBzjLPfAJboFMTnfbizhwO5t2QGI/edit)
- [ ] blog post
  - [ ] highlight modules and performance

# Post-Release follow-up
- [ ] document consistency
- [ ] switch over to internal usage of @xviz/io (examples, builders, parser etc)
- [ ] persistence flag + builder + buffer mgmt
- [ ] xviz cli convert cmd
- [ ] xviz server command // needs rfc

**Comment by twojtasz** [comment]
joe is working on his review of io & server
