### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by Pessimistress** [uber/xviz#7]
Documentation:

- [x] Clarify [Point3D](https://github.com/uber/xviz/blob/master/docs/protocol-schema/core-protocol.md) type vs. `point` primitive

Spec:

- [x] Add `Pose` type ({x, y, z, pitch, roll, yaw})
- [x] Add `Matrix4` type (column-major Number[16])
- [x] `coordinate` field in stream metadata (per-Stream Coordinate System) 
  + `geographic`
  + `map_relative`
  + `vehicle_relative`
  + `custom`
- [x] `pose` or `transformMatrix` field in stream metadata (per-Stream Coordinate System)
- [x] Specify `vehiclePose` structure
  + `origin` (coordinate)
  + `pose` (pose)
  + `mapPose` (pose, optional)
  + `customTransformMatrix` (matrix4, optional)

Parser:

- [ ] Support packed color array in addition to per-object color in point cloud
